export const GET_COMMON_POSITIONS = 'GET_COMMON_POSITIONS';
export const SET_CURRENT_POSITIONS = 'SET_CURRENT_POSITIONS';
export const GET_VARIANT_POSITIONS = 'GET_VARIANT_POSITIONS';
<<<<<<< HEAD
export const GET_FAVOURITE_POSITIONS = 'GET_FAVOURITE_POSITIONS';
=======

export const USER_AUTH = 'USER_AUTH';
>>>>>>> main
