export const GET_COMMON_POSITIONS = 'GET_COMMON_POSITIONS';
export const SET_CURRENT_POSITIONS = 'SET_CURRENT_POSITIONS';
export const GET_VARIANT_POSITIONS = 'GET_VARIANT_POSITIONS';
export const SET_VISIBLE_POSITIONS = 'SET_VISIBLE_POSITIONS';
