name: CI Server Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    name: Run Server Side Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: cd client && yarn install && yarn build
        env:
          MONGODB_CONNECTION: '${{ secrets.MONGODB_CONNECTION }}'